before:
  hooks:
    - go mod download
    - go generate ./...

builds:
  - main: ./
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
      format: zip
      files:
        - LICENSE*
        - README.md
        - c_elegans.json

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT-{{.ShortCommit}}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
