before:
  hooks:
  - go mod download

builds:
  - main: ./
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64

archive:
  replacements:
    amd64: 64-bit
    386: 32-bit
    darwin: macOS
  format: zip
  files:
    - LICENSE*
    - README.md
    - c_elegans.csv
